### ISSUE TITLE
I don't think we're in Kansas Anymore no waypoints

### ISSUE THREAD

**Issue by misuchiru03** [CounterHack/HolidayHack2017#10]
Waypoints are disappearing when I click "Roll", the bubble goes over where they would be, but since they are not there, they cannot be touched... so no points.  I'd screenshot it, but it's near impossible to see them anyway

**Comment by warquel** [comment]
Not a bug. This is part of the level.

**Comment by treefort** [comment]
@warquel is correct.

**Comment by pegasus2400** [comment]
Hello
Sorry
What is the number of waypoints in Kansas? I have reviewed the level completely and only find two.

**Comment by treefort** [comment]
There are three waypoints, total.

**Comment by pegasus2400** [comment]
Some clue to locate the third wayponit

**Comment by tkh16** [comment]
I can also confirm that there are three, though the third one is only visible through the poppies.  They blend in, but I suggest that you carefully look around with your camera low, looking for the bouncing.
