### ISSUE TITLE
bumbles bounce

### ISSUE THREAD

**Issue by digitalencoding** [CounterHack/HolidayHack2017#12]
after completing the Bumbles Bounce, I got the page of the great book but never got credit for the page or completing the level. I am also not getting credit (achievement) for finishing elftalkd even though I have the conveyor tool. 
____________________________________________________________________________
![img_2135](https://user-images.githubusercontent.com/34663357/34129882-6c745960-e40b-11e7-80f8-76549c9f17ee.JPG)

Find and run the elftalkd binary to complete this challenge.
**_REDACTED TO NOT GIVE ANYTHING AWAY_**
`elf@410b837df852:/blah/blah/blah$ ./elftalkd`

`Running in interactive mode`

`--== Initializing elftalkd ==--`
`Initializing Messaging System!`
`Nice-O-Meter configured to 0.90 sensitivity.`
`Acquiring messages from local networks...`

`--== Initialization Complete ==--`
`snip`
`-*> elftalkd! <*-`
`Version 9000.1 (Build 31337)`
`By Santa Claus & The Elf Team`
`Copyright (C) 2017 NotActuallyCopyrighted. No actual rights reserved.`
`Using libc6 version 2.23-0ubuntu9`
`LANG=en_US.UTF-8`
`Timezone=UTC`

____________________________________________________________________________

I have done a hard reset of the browser/cleared cache etc and given it time. @treefort  messaged me on Slack and says I have credit on the server end, but I don't have the achievements in my stocking or the Great Book page from the challenge.

Thanks,
Adam

**Comment by digitalencoding** [comment]
Hints  `36/36`
Tools  `6/7`
Chats  `1/2`
Achievements  `15/26`
Pages of the Great Book  `3/7`
Terminal challenges found  `8/8`

**Comment by digitalencoding** [comment]
Sorry, i had it edited trying to not give away the answer, should have edited it more.

**Comment by dpendolino** [comment]
@digitalencoding sorry for not responding sooner. We made some fixes to the token unlock and achievement code, would you please check again? Thank you!!

**Comment by digitalencoding** [comment]
@dpendolino no problem! I just did a hard reset on the browser, still not showing any more achievements or the 4th page of the book I should have.

**Comment by iagox86** [comment]
Hey @digitalencoding, I've looked at the stocking code and the database, and have verified that you SHOULD be seeing everything, you definitely have the tokens you said above.

Would you mind sharing screenshots of your stocking so we can see which ones are missing, and hopefully narrow it down?

Thanks!

**Comment by digitalencoding** [comment]
![screenshot from 2017-12-20 16-22-45](https://user-images.githubusercontent.com/34663357/34231611-60c5dd08-e5a2-11e7-82fb-e36fd4bd6223.png)

**Comment by digitalencoding** [comment]
I have pages 1, 2, and 5. I should have whatever page is on Bumbles Bounce and an Achievement for completing that level. I got 4 of the objectives completed in that level as well, my Achievements have been stuck at 15 for a few days no matter how many I complete in the snowball levels. I can copy the entire list if that will help, or post screenshots showing what ones I have showing, whatever will be more helpful

**Comment by digitalencoding** [comment]
![screenshot from 2017-12-20 16-29-34](https://user-images.githubusercontent.com/34663357/34231793-080dc418-e5a3-11e7-9ed2-1865ab2c84cf.png)
![screenshot from 2017-12-20 16-29-45](https://user-images.githubusercontent.com/34663357/34231794-08322f06-e5a3-11e7-94b9-27acf24d4904.png)

**Comment by iagox86** [comment]
For what it's worth, the problem where 100% achievement in a level doesn't grant the achievement is known and should be fixed next time we push (hopefully tonight).

I see you have every hint, which is what you get for exiting every level. You've unlocked one of the two NPC conversations, which seems right - you need to get more great book pages to unlock the other.

You're missing one tool, which you get from terminal challenge in level 6 - it looks like that one is so far incomplete.

The achievements are missing the 100% ones, which will be resolved soon, but it looks like you have the 8 for exiting levels and 7 of the 8 terminal challenges (number 6 is missing).

I believe everything you're supposed to have is there - other than the 100% completion achievements, but I could be missing something?

**Comment by digitalencoding** [comment]
well the main thing that I seem to be missing is the page from the great book on the bumbles bounce level

**Comment by digitalencoding** [comment]
And yes, there is one terminal challenge that I didn't complete on #6 "I Don't Think We're In Kansas Anymore," the sql one. I have achievements for all of the other terminals so that isn't an issue for me. I appreciate the help

**Comment by tkh16** [comment]
Isn't Page 5 the page from Bumble's Bounce?  It looks like you have it, unless I'm missing something.

**Comment by digitalencoding** [comment]
¯\_(ツ)_/¯ that is completely possible I guess @tkh16  maybe this was a completely unnecessary post, I didn't have credit for elftalkd, I just looked and I have 7/8 Achievements for terminals. There are 2 pages in the snowballs games, one on the l2s and the other pages are in the other servers? You can close this issue. 

Terminals
You've completed the Linux command hijacking terminal challenge!
You've completed the Web Log terminal challenge!
You've completed the Train Startup terminal challenge!
You've completed the Shadow File Restoration terminal challenge!
You've completed the isit42 terminal challenge!
You've completed the troublesome process terminal challenge!
You've completed the Candy Cane Striper terminal challenge!

Levels
Congratulations on making it to the exit of Oh Wait! Maybe we are…! Check out your stocking page for some hints!
Congratulations on making it to the exit of There's Snow Place Like Home! Check out your stocking page for some hints!
Congratulations on making it to the exit of Cryokinetic Magic! Check out your stocking page for some hints!
Congratulations on making it to the exit of Winconceivable: The Cliffs of Winsanity! Check out your stocking page for some hints!
Congratulations on making it to the exit of Winter Wonder Landing!
Congratulations on making it to the exit of I Don't Think We're In Kansas Anymore! Check out your stocking page for some hints!
Congratulations on making it to the exit of Bumbles Bounce! Check out your stocking page for some hints!
Congratulations 100% completion of We're Off to See the!

**Comment by iagox86** [comment]
That's correct - there are two pages (1 and 5) in the game, and you have both of those. The other 5 pages are in the various other non-game challenges.

Thanks for helping us figure things out! I'll go ahead and close this. Happy gaming!
