### ISSUE TITLE
Alabaster not invoking shells

### ISSUE THREAD

**Issue by pklanka** [CounterHack/HolidayHack2017#14]
Hi admin team

The shells are not getting invoked from Alabaster to elsewhere. The same document were working previously - but not anymore. I believe there is some limit that is preventing windows box to spawn shells. Could you please check. Please let me know where to send the document for your review.

regards
pklanka

**Comment by dpendolino** [comment]
@pklanka where are you trying to get a shell? Are you having trouble sshing in as alabaster?

**Comment by pklanka** [comment]
This is for q# 7. In EMI server, Alabaster is not clicking on the attachments. I believe there is a open process deluge preventing other processes from running on the machine.

**Comment by audibleblink** [comment]
@dpendolino Same here. Tried an attachment and got no callback. Just in case I messed up the document, I self hosted it and sent a link instead. No connections after a few hours. He doesn't seem to be following links in his email. Email has the required 3 keywords

**Comment by rinon** [comment]
Same, I get no connection back. Works fine locally.

**Comment by dpendolino** [comment]
@rinon @audibleblink We made some changes to the EMI server last evening, have you had any luck today?

**Comment by pklanka** [comment]
thanks for the changes. I was able to complete the challenge today morning 1 AM CT. Not by using usual "hint suggested" means. But Alabaster is checking emails. I can confirm.

**Comment by dpendolino** [comment]
@pklanka thanks for confirming and great job!!
