### ISSUE TITLE
Cranberry Pi crash on load

### ISSUE THREAD

**Issue by dickveal** [CounterHack/HolidayHack2017#17]
All the initial cranberry Pi's are displaying a crash when I access them.

I asked in chat to ensure this was not expected behaviour. See snip from crash below:

runtime/cgo: pthread_create failed: Resource temporarily unavailable
SIGABRT: abort
PC=0x7f2ba76f5fcf m=0 sigcode=18446744073709551610
goroutine 0 [idle]:

**Comment by dpendolino** [comment]
@dickveal thank you for the heads up, I've adjusted the config and things should be back now. Please let us know if you have any more trouble. Thanks!
