### ISSUE TITLE
Winconceivable: The Cliffs of Winsanity! Achievement

### ISSUE THREAD

**Issue by pegasus2400** [CounterHack/HolidayHack2017#18]
Hello

All the objectives of the level are shown as finished, however, it does not allow to unlock the achievement
<img width="664" alt="winconceivable" src="https://user-images.githubusercontent.com/34753111/34273826-987364a0-e65b-11e7-83be-eb7605b51cd7.png">

**Comment by tkh16** [comment]
Thanks for writing in!  We believe that we have fixed this problem.  Would you mind checking again to see if it's working as expected now?

**Comment by pegasus2400** [comment]
Thanks.
