### ISSUE TITLE
Not getting credit for completions

### ISSUE THREAD

**Issue by csgrv** [CounterHack/HolidayHack2017#19]
I have 100%ed all of the levels from an achievement perspective but am still missing 1 tool and 3 achievements on the scoreboard.    I have all terminals, all books, all conversations, all hints.  I logged in today and got a back log it looks like but ive tried to re-complete levels to get credit but no joy.

**Comment by dpendolino** [comment]
Hi @csgrv , would you mind attaching a screenshot of your stocking so we can take a look? Thanks!

**Comment by csgrv** [comment]
Attached is a screenshot of my stocking and play map
![stocking](https://user-images.githubusercontent.com/19586283/34306051-daf0c9ac-e706-11e7-8653-c93d0a7fa8ea.png)
![playmap](https://user-images.githubusercontent.com/19586283/34306052-dafbbb32-e706-11e7-807b-ed2a250dabd2.png)

**Comment by tkh16** [comment]
Hi @csgrv!  I checked into your account, and the missing achievements are related to terminal challenges.  A few of our terminal challenges weren't properly giving tokens at first...we've subsequently fixed the issue, but you may need to solve them again.  I'll follow up via e-mail to let you know the specific challenges involved.  Thanks for your understanding! (c:=
