### ISSUE TITLE
WebGL has problems on Firefox

### ISSUE THREAD

**Issue by tabascoeye** [CounterHack/HolidayHack2017#2]
I use Firefox WebDeveloper edition 58.0b10 and it has a problem with displaying the "ice" in the "Cryokinetic magic" level. The ice "surface" only displays for glitchy moments on certain camera angles. Most of the time, it's not rendered,
This makes it impossible to understand that you can't place tools on the ice. Maybe it's the reflection/glare of that surface?

**Comment by tabascoeye** [comment]
here is a screenshot:
![missing_lake](https://user-images.githubusercontent.com/111893/34045146-04890496-e1a8-11e7-87aa-a5f57346b454.png)

**Comment by dpendolino** [comment]
@tabascoeye thanks for reporting this! Do you see any errors in the JavaScript console? If you can attach a log, that would be super helpful. I know I've had the best results using Chrome or Chromium.

**Comment by tkh16** [comment]
I just tried that level in Firefox Developer edition 58.0b11, and the ice rendered fine for me (a bit sluggish, but it was there, even in a VM).  As @dpendolino suggested, any further logs or details about your system that you could offer would be greatly appreciated!

**Comment by tabascoeye** [comment]
Dang it. Of course, I can't reproduce it on my private machine :o(
Only had the problem on a machine that I won't touch until next year... *cough*...

**Comment by iagox86** [comment]
I'm going to mark this `resolved` for now. Please let us know if you're able to repro!
