### ISSUE TITLE
2 achievements with the same name

### ISSUE THREAD

**Issue by ankanani** [CounterHack/HolidayHack2017#21]
Hi
I notice 2 achievements with same name in the achievements list.
Congratulations 100% completion of We're Off to See the!
Congratulations 100% completion of We're Off to See the!

**Comment by tkh16** [comment]
Nice catch!  We accidentally put the wrong text into the achievement for reaching the exit in "We're Off To See the", which is why it appears that there are two 100% completion achievements.  We should have the text updated soon.

**Comment by tkh16** [comment]
This should now be fixed...please let us know if you see any further problems with this!  Thanks! (c:=
