### ISSUE TITLE
Possible wrong achievement in "we're off to see the ..."

### ISSUE THREAD

**Issue by gramou** [CounterHack/HolidayHack2017#23]
When I complete this level using normal exit, I get the achievement "Congratulations 100% completion of We're Off to See the!". The challenges " Unseat the villian." und "Guide the snowball over all waypoints in a single run." are unsolved. The level is marked with a green dot in the map. I guess, should get here a normal exit achievement?

**Comment by tkh16** [comment]
When you complete a level's exit objective, you get a green dot on the map.  If you complete _all_ objectives, you get a yellow dot.  Are you seeing a green dot or a yellow dot?

**Comment by gramou** [comment]
I see a green dot for "We're Off to See the", but I got the achievement "Congratulations 100% completion of We're Off to See the!".

**Comment by tkh16** [comment]
Could you please send us an e-mail at support@holidayhackchallenge.com with your player name and a screenshot of your Stocking so that we can look into this further?  Thanks!

**Comment by tkh16** [comment]
Thanks for the additional details!  For anyone else reading this, the text is wrong in one of those "100% completion" achievements...one of them should be for reaching the exit.  We should have the text updated soon.

**Comment by tkh16** [comment]
This should now be fixed...please let us know if you see any further problems with this!  Thanks! (c:=
