### ISSUE TITLE
EMI is at it again...

### ISSUE THREAD

**Issue by ryananicholson** [CounterHack/HolidayHack2017#29]
I was able to receive a shell with nc.exe a few days ago. I'm walking back through to do my write-up and am unable to get it to work again. Tried SEVERAL powershell payloads as well. They will download, but not execute. Works fine on a Windows 10 VM.

**Comment by dpendolino** [comment]
@ryananicholson I hope that you got it working, if not, please reach out!

**Comment by ryananicholson** [comment]
The same payload started working less than an hour after I posted the issue. Now that I think about it, both of my payloads worked later in the evening (~9PM EST), so maybe it's a server load issue?

**Comment by dpendolino** [comment]
Could be server issue, but for `nc` there is a known limitation where it will only work for a few players at a time.

**Comment by ryananicholson** [comment]
Totally makes sense and I'll remember this for next year... when attempting nc, wake up early ;)
