### ISSUE TITLE
Terminal Counter Off?

### ISSUE THREAD

**Issue by madclumsil33t** [CounterHack/HolidayHack2017#30]
I tried logging off/on and refreshing numerous times. After completing all terminals and getting all achievements in my stocking- my counter still shows 6/7 terminals complete?

**Comment by dpendolino** [comment]
@madclumsil33t can you tell us your username ( or email it to support@holidayhackchallenge.com) and which terminal appears to be missing? Thanks!

**Comment by madclumsil33t** [comment]
Sure- same as here. Madclumsil33t. The last term. i did was isit42. I got the congratulations and in my stocking I have the achievement saying "youve completed the isit42 terminal chllanenge!"

**Comment by dpendolino** [comment]
It looks like you're missing the completion achievement for the Train Startup terminal challenge, if you've completed it previously, would you mind trying again?

**Comment by madclumsil33t** [comment]
I have 7 "youve completed!... achievements. weird, Im sure you are right, I will go back and look. Thanks!
