### ISSUE TITLE
Not in Kansas ball game issue

### ISSUE THREAD

**Issue by emilyjr** [CounterHack/HolidayHack2017#31]
Hello,
I am hitting the roll button while in the "Not in Kansas Anymore" game and it just stays at loading. The balls never drop.

Happy New Year and thanks for this challenge.  
It is my first one and it is fun
Angie

**Comment by emilyjr** [comment]
Hello,
Please ignore my previous comment.  It just started working again.
Angie

**Comment by dpendolino** [comment]
Hi @emilyjr sorry for any inconvenience but that was likely an artifact of some urgent patching that just took place. Would you mind trying again and letting us know? Thank you!!

**Comment by dpendolino** [comment]
Awesome! Have fun =D
