### ISSUE TITLE
terminal challenge elftalkd

### ISSUE THREAD

**Issue by cynicXer** [CounterHack/HolidayHack2017#4]
this is popping up when i try to start the terminal:

/usr/bin/docker: Error response from daemon: oci runtime error: container_linux.go:265: starting container process caused "process_linux.go:368: container init caused \"could not create session key
: disk quota exceeded\"".

**Comment by dpendolino** [comment]
@cynicXer I just pushed a change which should resolve that error message. Try again and please let me know if it works. Thank you!!

**Comment by dpendolino** [comment]
Closing since this should be resolved, please let me know if it happens again.
