### ISSUE TITLE
Didn't get any reward after completing isit42 Terminal Challenge

### ISSUE THREAD

**Issue by oxcabe** [CounterHack/HolidayHack2017#6]

**Comment by warquel** [comment]
I can confirm this as well. There is no achievement after completing this terminal challenge.

**Comment by dpendolino** [comment]
@oxcabe @warquel Sorry for not responding sooner, but I tested and deployed a fix for this in the morning. If you redo the challenge, you should get the achievement. Would you mind trying one more time? Thank you!

**Comment by misuchiru03** [comment]
I got points last night where I didn't get any when this was a bug. I didn't get a pop-up telling me what was awarded though. I just had to go see my stocking and scoreboard for that info.

**Comment by warquel** [comment]
I too did not get a pop-up but the achievement is reflected in my Stocking.

**Comment by oxcabe** [comment]
I think it's fixed now. Closing this issue.
