### ISSUE TITLE
Bumbles Bounce not giving credit after landing on exit pad

### ISSUE THREAD

**Issue by farrellbj** [CounterHack/HolidayHack2017#7]
Two snowballs land on exit pad, no credit is given.
Running Chrome  63.0.3239.84

Showing the directionality change of the snowball after hitting the exit
![image](https://user-images.githubusercontent.com/23283388/34061406-82d2d3c8-e1e8-11e7-99dc-3a65541673e5.png)

And showing the lack of points
![image](https://user-images.githubusercontent.com/23283388/34061495-e63f1214-e1e8-11e7-939c-fced193d58e2.png)

**Comment by treefort** [comment]
Hey! We'll be pushing a fix for this shortly. Sorry about that!

**Comment by farrellbj** [comment]
Great!  Let me know and I can run the above screenshot to verify.

**Comment by treefort** [comment]
Will do!

**Comment by treefort** [comment]
@farrellbj should be fixed now—mind giving it a shot when you get a sec?

**Comment by farrellbj** [comment]
Works great now!  Thanks
